### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by udarts** [maksha/react-native-webhtmlview#2]
I am trying to display an image, but it only shows the alt text.
I checked the html, by alert the content, and it shows the image correctly.
So I am not sure why it is not showing.

**Comment by udarts** [comment]
BTW, I also display text with the image and the text is showing correctly.

**Comment by udarts** [comment]
Ah, I just found out that the image was on http and not https, is there a way to allow http or is that on ios something I need to set?

**Comment by maksha** [comment]
Hi @udarts, can you show part of your html source?

**Comment by udarts** [comment]
Sorry for the late reply.
I found out that on some android devices the image inside the html is not shown, it is on a http.
On most of the devices it is working.
Any idea why?

**Comment by maksha** [comment]
@udarts Could you please be more specific on what Android version / device that you use? I'm currently running an app using this component without any problem displaying images. 

I'm going to close this issue, please re-open it if you still have problem.
